version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:password@db:5432/db_name

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
